steps:
  - name: Build container image
    agents:
      queue: default
      os: linux
    plugins:
      - EmbarkStudios/k8s#0.9.2:
          image: gcr.io/kaniko-project/executor:latest
          command:
            - --destination=embarkstudios/wireguard-ui
            - --context=dir://$PWD
            - --reproducible
            - --cache=true
            - --cache-repo=kaniko-cache.buildkite.svc.cluster.local/kaniko/cache
            - --cache-dir=$BUILDKITE_BUILD_PATH/_kaniko_cache
          mount-secret:
            - docker-hub-credentials:/kaniko/.docker
