name: Go
on: 
  push:
    branches-ignore: master
  pull_request:
    branches:
      - master
jobs:
  review:
    name: Review code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: bindfs
      uses: "cedrickring/golang-action@1.4.1"
      with:
        args: go get -u github.com/go-bindata/go-bindata/... && go get -u github.com/elazarl/go-bindata-assetfs/... && go-bindata-assetfs -prefix ui/dist ui/dist
    - name: Check styling error
      uses: "cedrickring/golang-action@1.4.1"
      with:
        args: go get -u golang.org/x/lint/golint; golint -set_exit_status main.go server.go config.go # ./... update to use package when https://github.com/go-bindata/go-bindata/pull/37 is merged
    - name: Check missing error check
      uses: "cedrickring/golang-action@1.4.1"
      with:
        args: go get -u github.com/kisielk/errcheck; errcheck ./...
    - name: Check suspicious constructs (1)
      uses: "cedrickring/golang-action@1.4.1"
      with:
        args: go get honnef.co/go/tools/cmd/staticcheck; staticcheck -checks all,-ST1003,-U1000,-ST1005 ./... # have to disable ST1003,U1000,ST1005 due to the generated code
    - name: Check suspicious constructs (2)
      uses: "cedrickring/golang-action@1.4.1"
      with:
        args: go vet ./...
    - name: Check missing error check
      uses: "cedrickring/golang-action@1.4.1"
      with:
        args: go get github.com/securego/gosec/cmd/gosec; gosec ./... # https://github.com/securego/gosec
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        #docker rmi $(docker image ls -aq)
        df -h
    - name: Install buildah
      run: |
        sudo apt-get install -qq -y software-properties-common
        sudo add-apt-repository -y ppa:projectatomic/ppa
        sudo apt-get update -qq
        sudo apt-get -qq -y install buildah
    - name: Build the Docker image
      run: buildah bud --format=docker --layers -f Dockerfile .
